name: CI

on:
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build Registry
        run: bun build:registry

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase
        run: supabase start

      - name: Dump Supabase env (with overridden key names)
        run: |
          supabase status -o env \
            --override-name api.url=PUBLIC_SUPABASE_URL \
            --override-name auth.anon_key=PUBLIC_SUPABASE_ANON_KEY \
            --override-name auth.service_role_key=SUPABASE_SERVICE_KEY \
            > .env
      - name: build and run
        run: bun run build && bun run preview

      - name: Run Playwright tests
        run: bunx playwright test --config playwright.ci.config.ts


      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

