name: CI

on:
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Build frontend
        run: bun run build

      - name: Svelte run
        run: bun run preview --port 5173

      - name: Run Playwright tests
        run: bunx playwright test

      - name: Build Registry
        run: bun build:registry

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

